words = [
    "actix",
    "aitvann",
    "aitzhanov",
    "dsl",
    "hashi",
    "linkedin",
    "poselok",
    "raydium",
    "rustenger",
    "tokio",
    "tradetech",
    "wargaming",
    "ПУ",
    "СПб",
]
